// AKENO STREAM PS5 - Controller input: raw DualSense samples to UI events.
// Copyright (C) 2026 AKENO STREAM contributors
// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <cstdint>
#include <vector>

namespace akeno::input
{
// scePad button bits (layout shared with ps5-homebrew-ui and ProsperoTV).
namespace bits
{
constexpr std::uint32_t l3 = 0x00000002;
constexpr std::uint32_t r3 = 0x00000004;
constexpr std::uint32_t options = 0x00000008;
constexpr std::uint32_t up = 0x00000010;
constexpr std::uint32_t right = 0x00000020;
constexpr std::uint32_t down = 0x00000040;
constexpr std::uint32_t left = 0x00000080;
constexpr std::uint32_t l2 = 0x00000100;
constexpr std::uint32_t r2 = 0x00000200;
constexpr std::uint32_t l1 = 0x00000400;
constexpr std::uint32_t r1 = 0x00000800;
constexpr std::uint32_t triangle = 0x00001000;
constexpr std::uint32_t circle = 0x00002000;
constexpr std::uint32_t cross = 0x00004000;
constexpr std::uint32_t square = 0x00008000;
constexpr std::uint32_t touchpad = 0x00100000;
// Set while the system UI (PS button menu, notifications) owns the pad.
constexpr std::uint32_t intercepted = 0x80000000;
} // namespace bits

enum class Button : std::uint8_t
{
    up,
    down,
    left,
    right,
    cross,
    circle,
    square,
    triangle,
    l1,
    r1,
    l2,
    r2,
    options,
    touchpad,
    l3,
    r3,
};

struct Event
{
    Button button;
    bool repeat = false; // generated by holding a direction
};

struct Sample
{
    std::uint32_t buttons = 0;
    std::uint8_t left_x = 128, left_y = 128;
    bool connected = true;
};

// Turns successive pad samples into press events. Directions (d-pad or left
// stick) repeat while held; other buttons fire once per press. Input received
// while the system UI intercepts the pad, or while disconnected, is dropped
// and does not produce stale presses later.
class Mapper final
{
  public:
    static constexpr std::uint64_t kRepeatDelayMs = 380;
    static constexpr std::uint64_t kRepeatIntervalMs = 110;
    static constexpr std::uint64_t kFastIntervalMs = 55; // after holding for kFastAfterMs
    static constexpr std::uint64_t kFastAfterMs = 1800;
    static constexpr int kStickDeadzone = 70;

    void feed(const Sample &sample, std::uint64_t now_ms, std::vector<Event> &out);
    // Emits repeats when no new sample arrived (the pad only reports changes).
    void tick(std::uint64_t now_ms, std::vector<Event> &out);
    void reset() noexcept;
    [[nodiscard]] bool connected() const noexcept
    {
        return connected_;
    }

  private:
    std::uint32_t previous_ = 0;
    int held_direction_ = -1;
    std::uint64_t held_since_ = 0;
    std::uint64_t next_repeat_ = 0;
    bool connected_ = false;
};
} // namespace akeno::input
